services:
  db:
    image: pgvector/pgvector:pg16
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: shop_bot
    restart: always
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/shop_db


  vectorizer:
    build: .
    container_name: shop_vectorizer
    restart: always
    command: python -m app.services.vector_manager
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/shop_db

volumes:
  pg_data: